name = "The Everwild"
author = "Zenfrii"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7caf883adb831e880524f69b325d1379d97ac683d11d80a25ed51f1ff3bfe415"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
