name = "The Everwild"
author = "Zenfrii"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2685a7a811dd60639c77c31baba8cdfd818b24a171513436470ea3526f74a73"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
